// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// 位置記録 platform channel の型定義（Issue #124・T049）。
///
/// `specs/001-mvp/plan.md` §1-C の決定 C「機微処理（背景位置・fused location・
/// モック検出・Play Integrity・歩数センサーはOS別実装が本質）」に基づき、
/// Pigeon の channel 契約ファイルを **iOS 移植の正** とする（advisor 評価：
/// 「Pigeon の channel 契約ファイルを iOS 移植の正とし、Dart 側ロジックは共通化する」）。
///
/// ## ⚠️ なぜ位置データそのものをここに含めないか（Issue #124 起票時の論点・本 Issue で決定）
/// `docs/location-track-db.md` §2・§3 は、位置記録ファイル `location_track.sqlite` を
/// Dart 側から直接読み取り専用で開く方法（`NativePositionProvider`・
/// `packages/location/lib/src/db/location_track_connection.dart`）を推奨している。
/// 本 Pigeon ファイルは**位置データ（緯度経度・時刻・精度）を1件も運ばない**。
/// 代わりに運ぶのは、位置記録 foreground service（PR #128・`LocationTrackingService`）の
/// **起動・停止・状態問い合わせという制御面**だけである。
///
/// 理由:
/// 1. **効率**: 位置データは記録が進むにつれて増え続ける。Pigeon（1呼び出し1メッセージ）で
///    1件ずつ運ぶより、まとまった単位でファイルを直接読む方が単純かつ効率的であり、
///    `docs/location-track-db.md` が既にその経路（`app_flutter/` 配下の共有ディレクトリに
///    Kotlin/Dart 双方がアクセスできる）を確立している。
/// 2. **64bit整数の丸め問題を経路自体から排除する**（`docs/terrain.md` §4.4・Issue #124
///    本文「⚠️ 64bit整数の受け渡し」）。位置記録の `elapsed_realtime_nanos`
///    （実機で `2634654803000000` 程度の値を確認済み）はJSON系の経路で2^53を超えて
///    丸められる恐れがあるが、本ファイルのメッセージ型は**64bit整数を一切含まない**
///    ため、この経路では問題が発生しようがない。SQLite 経由の64bit値は
///    Dart のネイティブ `int`（VM上は64bit）でそのまま読める
///    （`native_position_provider_test.dart`・`location_track_connection_test.dart`
///    で丸めが起きないことを確認する）。
/// 3. **スコープの厳守**: Kotlin foreground service 本体（PR #128）の実装・スキーマを
///    変更せずに済む。位置データの受け渡し方法は Issue #123 の時点で既に確定している
///    （`docs/location-track-db.md`）。
///
/// 一方で、次の3つは位置データではなく「サービスの制御・状態」であり、
/// ファイル読み取りでは表現できない（ファイルには「今まさに稼働中か」
/// 「起動要求がなぜ失敗したか」は記録されない）ため、Pigeon で渡す:
/// - サービスの起動・停止（[LocationTrackingHostApi.startTracking]・
///   [LocationTrackingHostApi.stopTracking]）。現状はデバッグ用 Intent
///   （`MainActivity.handleDebugLocationServiceIntent`）でしか起動できない。
/// - サービスの状態（稼働中か・現在の `session_id`。
///   [LocationTrackingHostApi.getTrackingStatus]）。
/// - 起動しなかった理由（[TrackingStartOutcome.permissionDenied]）。
enum TrackingStartOutcome {
  /// フォアグラウンド位置権限（`ACCESS_FINE_LOCATION`/`ACCESS_COARSE_LOCATION`）が
  /// 確認でき、位置記録 foreground service の起動を要求した
  /// （`Context#startForegroundService()` を呼んだ、という意味。実際に
  /// `startForeground()` まで到達したかはこの結果からは分からない。稼働状態の
  /// 確認は [LocationTrackingHostApi.getTrackingStatus] を使うこと）。
  started,
  /// フォアグラウンド位置権限が無いため、`startForegroundService()` 自体を
  /// **呼ばずに**起動を拒否した。
  ///
  /// **なぜこの区別が安全性に直結するか**: 権限が無い場合に
  /// `Context#startForegroundService()` を呼んでしまうと、システムは一定時間内の
  /// `Service.startForeground()` 呼び出しを義務づけるため、権限チェックを
  /// サービス内部だけに任せると `ForegroundServiceDidNotStartInTimeException` で
  /// アプリのプロセスごと強制終了されうる
  /// （2026-09-11 実機検証・Pixel 7a・PR #128 のレビューコメントで確認済み）。
  ///
  /// この修正（`LocationTrackingService.Companion.start()` 側で権限を確認し、
  /// 権限が無ければ `startForegroundService()` 自体を呼ばず `Boolean` の戻り値で
  /// 呼び出し側に通知する）は **PR #130（2026-09-11 マージ）で main に反映済み**。
  /// 本 Pigeon ハンドラ（`LocationApiHandler.kt`）は `Companion.start()` の戻り値を
  /// そのままこの結果に変換するだけで、自前の権限チェックは行わない。
  permissionDenied,
}

class TrackingStartResult {
  TrackingStartResult({
    required this.outcome,
  });

  TrackingStartOutcome outcome;

  List<Object?> _toList() {
    return <Object?>[
      outcome,
    ];
  }

  Object encode() {
    return _toList();  }

  static TrackingStartResult decode(Object result) {
    result as List<Object?>;
    return TrackingStartResult(
      outcome: result[0]! as TrackingStartOutcome,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrackingStartResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrackingStartResult(outcome: $outcome)';
  }
}

class TrackingStatus {
  TrackingStatus({
    required this.isRunning,
    this.sessionId,
  });

  /// 位置記録 foreground service が現在稼働中か
  /// （`startForeground()` まで到達した状態を指す。権限拒否で拒否された場合は false）。
  bool isRunning;

  /// 稼働中の場合の記録セッションID。
  ///
  /// `location_track.sqlite` の `location_point.session_id` 列、および
  /// `GeoPosition.trackingSessionId`（`packages/core`・本 Issue で追加）と同じ値。
  /// 未稼働時は null。
  String? sessionId;

  List<Object?> _toList() {
    return <Object?>[
      isRunning,
      sessionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static TrackingStatus decode(Object result) {
    result as List<Object?>;
    return TrackingStatus(
      isRunning: result[0]! as bool,
      sessionId: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrackingStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isRunning, other.isRunning) && _deepEquals(sessionId, other.sessionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrackingStatus(isRunning: $isRunning, sessionId: $sessionId)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TrackingStartOutcome) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is TrackingStartResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is TrackingStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : TrackingStartOutcome.values[value];
      case 130:
        return TrackingStartResult.decode(readValue(buffer)!);
      case 131:
        return TrackingStatus.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LocationTrackingHostApi {
  /// Constructor for [LocationTrackingHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LocationTrackingHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 位置記録 foreground service の起動を要求する。
  ///
  /// フォアグラウンド位置権限が無い場合は [TrackingStartOutcome.permissionDenied] を
  /// 返し、`startForegroundService()` 自体を呼ばない（[TrackingStartOutcome] の
  /// ドキュメント参照）。
  Future<TrackingStartResult> startTracking() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.terra_town_location.LocationTrackingHostApi.startTracking$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as TrackingStartResult;
  }

  /// 位置記録 foreground service の停止を要求する。
  Future<void> stopTracking() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.terra_town_location.LocationTrackingHostApi.stopTracking$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 現在の稼働状態を問い合わせる。
  Future<TrackingStatus> getTrackingStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.terra_town_location.LocationTrackingHostApi.getTrackingStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as TrackingStatus;
  }
}
