// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package jp.rokusoudo.terra_town.savedata

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object SaveDataApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class SaveDataApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * セーブデータのエクスポート/インポート（Issue #180・T105）で、Android の
 * ストレージ・アクセス・フレームワーク（SAF）経由のファイル保存/読み込みを行う
 * platform channel の型定義。
 *
 * ## なぜ `pigeons/location_api.dart` と同じ Pigeon の仕組みを使うか（採用方式・PR本文にも記載）
 * Issue #180 決定事項6は、ファイル受け渡しの実現方法として次の二択を示している。
 * - (a) `app` 層のプラグイン（`file_selector`・`share_plus`・`file_picker` 等）
 * - (b) Pigeon → Kotlin の `ACTION_CREATE_DOCUMENT`／`ACTION_OPEN_DOCUMENT`
 *
 * **本ファイルは (b) を採用する。** 理由（advisor相談・2026-09-14）:
 * 1. **新しい Gradle プラグインを追加しない。** `packages/location/pubspec.yaml` の
 *    `maplibre_gl` に関する記録（Issue #67）が示すとおり、このリポジトリでは
 *    Flutter プラグインの追加が Kotlin ツールチェーンの相互排他で実際にビルドを
 *    壊した前例がある。`file_selector`・`share_plus` 等の新規プラグインを
 *    追加するリスクを冒すより、既存の Pigeon（`LocationTrackingHostApi`）と
 *    同じ仕組みを拡張する方が安全である。
 * 2. 保存・読み込みの両方を**一貫した1つの仕組み**で実装できる。決定事項6が
 *    「file_selector の保存 **or** share_plus」と二択で書いているのは、
 *    候補プラグインの組み合わせによって保存側・読み込み側の実装元が分かれうる
 *    ためだが、Pigeon → Kotlin なら両方向を同じハンドラ・同じ Activity で
 *    完結できる。
 * 3. Dart は `content://` URI のバイト列を直接読み書きできないため、
 *    いずれの案でも最終的には Kotlin（`ContentResolver`）側での I/O が必要になる。
 *
 * ## `Activity` を保持する理由（`LocationApiHandler` との違い）
 * `LocationApiHandler` は `Context`（`applicationContext`）だけで完結するが、
 * 本ハンドラ（`SaveDataApiHandler.kt`）は `startActivityForResult`/
 * `onActivityResult` という **Activity のライフサイクルに紐づく API** を使うため、
 * `Activity`（`MainActivity` 自身）を保持する。`FlutterActivity` は
 * `android.app.Activity` を継承しているため、`FlutterFragmentActivity` へ切り替え
 * なくてもこの古典的な API がそのまま使える。
 *
 * ## `@async` の意味（`LocationApiHandler` とは異なる非同期の理由）
 * [getLocationPoints] 等の `@async` はブロッキング I/O をメインスレッド外で
 * 行うためだが、本ファイルの `@async` は **ユーザーがピッカーを操作し終えるまで
 * Dart 側の呼び出しを待たせる**ため（`onActivityResult` が呼ばれるまで
 * `suspendCancellableCoroutine` で一時停止する）。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SaveDataFileHostApi {
  /**
   * SAF の `ACTION_CREATE_DOCUMENT` でユーザーに保存先を選ばせ、[contents] を
   * UTF-8 で書き込む。
   *
   * [suggestedFileName] は既定のファイル名（例:
   * `terra-town-save-20260914-1200.json`）。ユーザーがピッカーをキャンセルした
   * 場合は書き込みを行わず `false` を返す。書き込み自体が失敗した場合（I/O
   * 例外）は例外を投げる。
   */
  suspend fun saveTextFile(suggestedFileName: String, contents: String): Boolean
  /**
   * SAF の `ACTION_OPEN_DOCUMENT` でユーザーにファイルを選ばせ、内容を UTF-8
   * として読み込む。
   *
   * MIME タイプでの絞り込みは行わない（ファイルマネージャーによって `.json` の
   * MIME タイプの報告が `application/json`／`application/octet-stream`／`text/plain`
   * など揺れるため、OS 側のフィルタに頼らず内容自体をアプリ側で検証する方針
   * ——`packages/location/lib/src/save_data/` の JSON 検証ロジック参照）。
   * ユーザーがピッカーをキャンセルした場合は `null` を返す。読み込み自体が
   * 失敗した場合（I/O 例外・UTF-8 として解釈できない）は例外を投げる。
   */
  suspend fun openTextFile(): String?

  companion object {
    /** The codec used by SaveDataFileHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SaveDataApiPigeonCodec()
    }
    /** Sets up an instance of `SaveDataFileHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SaveDataFileHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.terra_town_location.SaveDataFileHostApi.saveTextFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val suggestedFileNameArg = args[0] as String
            val contentsArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.saveTextFile(suggestedFileNameArg, contentsArg))
              } catch (exception: Throwable) {
                SaveDataApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.terra_town_location.SaveDataFileHostApi.openTextFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.openTextFile())
              } catch (exception: Throwable) {
                SaveDataApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
