// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package jp.rokusoudo.terra_town.location

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LocationApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * 位置記録 platform channel の型定義（Issue #124・T049）。
 *
 * `specs/001-mvp/plan.md` §1-C の決定 C「機微処理（背景位置・fused location・
 * モック検出・Play Integrity・歩数センサーはOS別実装が本質）」に基づき、
 * Pigeon の channel 契約ファイルを **iOS 移植の正** とする（advisor 評価：
 * 「Pigeon の channel 契約ファイルを iOS 移植の正とし、Dart 側ロジックは共通化する」）。
 *
 * ## ⚠️ なぜ位置データそのものをここに含めないか（Issue #124 起票時の論点・本 Issue で決定）
 * `docs/location-track-db.md` §2・§3 は、位置記録ファイル `location_track.sqlite` を
 * Dart 側から直接読み取り専用で開く方法（`NativePositionProvider`・
 * `packages/location/lib/src/db/location_track_connection.dart`）を推奨している。
 * 本 Pigeon ファイルは**位置データ（緯度経度・時刻・精度）を1件も運ばない**。
 * 代わりに運ぶのは、位置記録 foreground service（PR #128・`LocationTrackingService`）の
 * **起動・停止・状態問い合わせという制御面**だけである。
 *
 * 理由:
 * 1. **効率**: 位置データは記録が進むにつれて増え続ける。Pigeon（1呼び出し1メッセージ）で
 *    1件ずつ運ぶより、まとまった単位でファイルを直接読む方が単純かつ効率的であり、
 *    `docs/location-track-db.md` が既にその経路（`app_flutter/` 配下の共有ディレクトリに
 *    Kotlin/Dart 双方がアクセスできる）を確立している。
 * 2. **64bit整数の丸め問題を経路自体から排除する**（`docs/terrain.md` §4.4・Issue #124
 *    本文「⚠️ 64bit整数の受け渡し」）。位置記録の `elapsed_realtime_nanos`
 *    （実機で `2634654803000000` 程度の値を確認済み）はJSON系の経路で2^53を超えて
 *    丸められる恐れがあるが、本ファイルのメッセージ型は**64bit整数を一切含まない**
 *    ため、この経路では問題が発生しようがない。SQLite 経由の64bit値は
 *    Dart のネイティブ `int`（VM上は64bit）でそのまま読める
 *    （`native_position_provider_test.dart`・`location_track_connection_test.dart`
 *    で丸めが起きないことを確認する）。
 * 3. **スコープの厳守**: Kotlin foreground service 本体（PR #128）の実装・スキーマを
 *    変更せずに済む。位置データの受け渡し方法は Issue #123 の時点で既に確定している
 *    （`docs/location-track-db.md`）。
 *
 * 一方で、次の3つは位置データではなく「サービスの制御・状態」であり、
 * ファイル読み取りでは表現できない（ファイルには「今まさに稼働中か」
 * 「起動要求がなぜ失敗したか」は記録されない）ため、Pigeon で渡す:
 * - サービスの起動・停止（[LocationTrackingHostApi.startTracking]・
 *   [LocationTrackingHostApi.stopTracking]）。現状はデバッグ用 Intent
 *   （`MainActivity.handleDebugLocationServiceIntent`）でしか起動できない。
 * - サービスの状態（稼働中か・現在の `session_id`。
 *   [LocationTrackingHostApi.getTrackingStatus]）。
 * - 起動しなかった理由（[TrackingStartOutcome.permissionDenied]）。
 */
enum class TrackingStartOutcome(val raw: Int) {
  /**
   * フォアグラウンド位置権限（`ACCESS_FINE_LOCATION`/`ACCESS_COARSE_LOCATION`）が
   * 確認でき、位置記録 foreground service の起動を要求した
   * （`Context#startForegroundService()` を呼んだ、という意味。実際に
   * `startForeground()` まで到達したかはこの結果からは分からない。稼働状態の
   * 確認は [LocationTrackingHostApi.getTrackingStatus] を使うこと）。
   */
  STARTED(0),
  /**
   * フォアグラウンド位置権限が無いため、`startForegroundService()` 自体を
   * **呼ばずに**起動を拒否した。
   *
   * **なぜこの区別が安全性に直結するか**: `LocationTrackingService.onStartCommand`
   * は権限が無い場合 `startForeground()` を呼ばずに `stopSelf()` する実装だが、
   * `Context#startForegroundService()` を一度でも呼ぶと、システムは一定時間内の
   * `startForeground()` 呼び出しを義務づける。権限が無くサービス内部で
   * `startForeground()` を呼べない場合、`ForegroundServiceDidNotStartInTimeException`
   * でアプリのプロセスごと強制終了される
   * （2026-09-11 実機検証・Pixel 7a・PR #128 のレビューコメントで確認済み）。
   *
   * **⚠️ 要確認（本 Issue のスコープ外・PR本文に記載）**: この修正を含む
   * コミット（`17dead3`）は `feature/issue-123-kotlin-location-fgs` ブランチに
   * 存在するが、**PR #128 がマージされた main には含まれていない**
   * （2026-09-11 に本 Issue の実装時に発覚。PR #128 は `mergedAt` より後の
   * タイムスタンプでこのブランチに追加コミットが積まれており、再マージされていない）。
   * そのため、本 Pigeon ハンドラ（`LocationApiHandler.kt`）は
   * `LocationTrackingService.Companion.start()` を直接呼ばず、
   * `LocationTrackingService.hasForegroundLocationPermission()` を**呼び出し側で
   * 先に確認してから** `start()` を呼ぶことで、Pigeon 経由の起動要求に限っては
   * このクラッシュを回避している。ただし既存のデバッグ用 adb Intent
   * （`MainActivity.handleDebugLocationServiceIntent`）はこの権限確認を経由しない
   * ため、**main 上では権限拒否状態で adb Intent 経由の起動を行うと今も
   * クラッシュする**。秘書セッションの実機確認手順は Pigeon 経由（本APIの
   * `startTracking`）を使うこと（PR本文参照）。
   */
  PERMISSION_DENIED(1);

  companion object {
    fun ofRaw(raw: Int): TrackingStartOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrackingStartResult (
  val outcome: TrackingStartOutcome
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackingStartResult {
      val outcome = pigeonVar_list[0] as TrackingStartOutcome
      return TrackingStartResult(outcome)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outcome,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrackingStartResult
    return LocationApiPigeonUtils.deepEquals(this.outcome, other.outcome)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocationApiPigeonUtils.deepHash(this.outcome)
    return result
  }
  override fun toString(): String {
    return "TrackingStartResult(outcome=$outcome)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrackingStatus (
  /**
   * 位置記録 foreground service が現在稼働中か
   * （`startForeground()` まで到達した状態を指す。権限拒否で拒否された場合は false）。
   */
  val isRunning: Boolean,
  /**
   * 稼働中の場合の記録セッションID。
   *
   * `location_track.sqlite` の `location_point.session_id` 列、および
   * `GeoPosition.trackingSessionId`（`packages/core`・本 Issue で追加）と同じ値。
   * 未稼働時は null。
   */
  val sessionId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackingStatus {
      val isRunning = pigeonVar_list[0] as Boolean
      val sessionId = pigeonVar_list[1] as String?
      return TrackingStatus(isRunning, sessionId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isRunning,
      sessionId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrackingStatus
    return LocationApiPigeonUtils.deepEquals(this.isRunning, other.isRunning) && LocationApiPigeonUtils.deepEquals(this.sessionId, other.sessionId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocationApiPigeonUtils.deepHash(this.isRunning)
    result = 31 * result + LocationApiPigeonUtils.deepHash(this.sessionId)
    return result
  }
  override fun toString(): String {
    return "TrackingStatus(isRunning=$isRunning, sessionId=$sessionId)"
  }
}
private open class LocationApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TrackingStartOutcome.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackingStartResult.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackingStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TrackingStartOutcome -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is TrackingStartResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TrackingStatus -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LocationTrackingHostApi {
  /**
   * 位置記録 foreground service の起動を要求する。
   *
   * フォアグラウンド位置権限が無い場合は [TrackingStartOutcome.permissionDenied] を
   * 返し、`startForegroundService()` 自体を呼ばない（[TrackingStartOutcome] の
   * ドキュメント参照）。
   */
  fun startTracking(): TrackingStartResult
  /** 位置記録 foreground service の停止を要求する。 */
  fun stopTracking()
  /** 現在の稼働状態を問い合わせる。 */
  fun getTrackingStatus(): TrackingStatus

  companion object {
    /** The codec used by LocationTrackingHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocationApiPigeonCodec()
    }
    /** Sets up an instance of `LocationTrackingHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocationTrackingHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.terra_town_location.LocationTrackingHostApi.startTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.startTracking())
            } catch (exception: Throwable) {
              LocationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.terra_town_location.LocationTrackingHostApi.stopTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopTracking()
              listOf(null)
            } catch (exception: Throwable) {
              LocationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.terra_town_location.LocationTrackingHostApi.getTrackingStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getTrackingStatus())
            } catch (exception: Throwable) {
              LocationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
